# Generated by Django 5.1.4 on 2025-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysqltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
