# Generated by Django 5.1.4 on 2025-01-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderss',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('receipt', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
