# Generated by Django 5.1.4 on 2025-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_orderss'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderss',
            name='payment_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
