# Generated by Django 5.1.4 on 2025-01-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_orderss_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField()),
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('products', models.TextField()),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=50)),
                ('receipt', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='orderss',
            options={'managed': False},
        ),
    ]
